version: 0.2

phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws --version
      - docker --version
      - ECR_REGISTRY="$(echo "$ECR_REPO_URI" | cut -d/ -f1)"
      - aws ecr get-login-password --region "$AWS_DEFAULT_REGION" | docker login --username AWS --password-stdin "$ECR_REGISTRY"
      - IMAGE_TAG="$(echo "$CODEBUILD_RESOLVED_SOURCE_VERSION" | cut -c1-12)"
      - echo "Image tag: $IMAGE_TAG"
  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t "$ECR_REPO_URI:$IMAGE_TAG" -t "$ECR_REPO_URI:latest" -f projects/simple-site/Dockerfile projects/simple-site
  post_build:
    commands:
      - echo "Pushing Docker images..."
      - docker push "$ECR_REPO_URI:$IMAGE_TAG"
      - docker push "$ECR_REPO_URI:latest"
      - echo "Writing imagedefinitions.json for ECS deploy..."
      - printf '[{"name":"%s","imageUri":"%s"}]' "app" "$ECR_REPO_URI:$IMAGE_TAG" > imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json

