FROM nginx:1.25-alpine

# Static site content
COPY index.html /usr/share/nginx/html/index.html
COPY IMG_2317.jpeg /usr/share/nginx/html/IMG_2317.jpeg
COPY design-1 /usr/share/nginx/html/design-1

# NGINX listens on 80 by default
EXPOSE 80

